### ISSUE TITLE
issues running ppjsdm on datasets

### ISSUE THREAD

**Issue by pvesk** [iflint1/ppjsdm_on_datasets#1]
Hi IAn, trying to run the vignettes, and repeated getting this errror:
Error in missing(dummy) : 'missing' can only be used for arguments

**Comment by iflint1** [comment]
Thanks for reminding me to update the package. This was due to a recently introduced bug in `ppjsdm`, fixed in [the most recent commit](https://github.com/iflint1/ppjsdm/commit/2e50f7767bb69744d325fd76041dd26da601eab2). Please update your `ppjsdm` package.

I also updated all the vignettes since I have changed the `ppjsdm` interface since when I wrote `ppjsdm_on_datasets`. Update `ppjsdm_on_datasets` and everything should work!

**Comment by pvesk** [comment]
terrific, sorted.
